--- Makefile_old	2021-05-29 15:26:55.962231500 +0200
+++ Makefile	2021-05-30 18:19:05.732631200 +0200
@@ -1,5 +1,21 @@
 include ../config.inc
 
+ifneq ($(PARAFROSTCPU),)
+  PARAFROST_SRC  = sat/satcheck-parafrost/satcheck_parafrost.cpp
+  PARAFROST_SRC += sat/satcheck-parafrost/parafrost_config.cpp
+  PARAFROST_INCLUDE=-I $(PARAFROSTCPU)/src/cpu
+  PARAFROST_LIB=$(PARAFROSTCPU)/build/cpu/libparafrost$(LIBEXT)
+  CP_CXXFLAGS += -DHAVE_PARAFROST
+endif
+
+ifneq ($(PARAFROSTGPU),)
+  PARAFROST_SRC  = sat/satcheck-parafrost/satcheck_parafrost.cpp
+  PARAFROST_SRC += sat/satcheck-parafrost/parafrost_config.cpp
+  PARAFROST_INCLUDE=-I $(PARAFROSTGPU)/src/gpu
+  PARAFROST_LIB=$(PARAFROSTGPU)/build/gpu/libparafrost$(LIBEXT)
+  CP_CXXFLAGS += -DHAVE_PARAFROST
+endif
+
 ifneq ($(CHAFF),)
   CHAFF_SRC=sat/satcheck_zchaff.cpp sat/satcheck_zcore.cpp
   CHAFF_INCLUDE=-I $(CHAFF)
@@ -79,6 +95,7 @@
       $(PICOSAT_SRC) \
       $(SQUOLEM2_SRC) \
       $(CADICAL_SRC) \
+	  $(PARAFROST_SRC) \
       decision_procedure.cpp \
       solver_hardness.cpp \
       flattening/arrays.cpp \
@@ -227,7 +244,7 @@
   $(CHAFF_INCLUDE) $(BOOLEFORCE_INCLUDE) $(MINISAT_INCLUDE) $(MINISAT2_INCLUDE) \
   $(IPASIR_INCLUDE) \
   $(SQUOLEM2_INC) $(CUDD_INCLUDE) $(GLUCOSE_INCLUDE) \
-	$(PICOSAT_INCLUDE) $(LINGELING_INCLUDE) $(CADICAL_INCLUDE)
+	$(PICOSAT_INCLUDE) $(LINGELING_INCLUDE) $(CADICAL_INCLUDE) $(PARAFROST_INCLUDE)
 
 CLEANFILES += solvers$(LIBEXT) \
   smt2_solver$(EXEEXT) smt2/smt2_solver$(OBJEXT) smt2/smt2_solver$(DEPEXT)
@@ -244,7 +261,7 @@
 
 SOLVER_LIB = $(CHAFF_LIB) $(BOOLEFORCE_LIB) $(MINISAT_LIB) \
         $(MINISAT2_LIB) $(SQUOLEM2_LIB) $(CUDD_LIB) \
-        $(PICOSAT_LIB) $(LINGELING_LIB) $(GLUCOSE_LIB) $(CADICAL_LIB)
+        $(PICOSAT_LIB) $(LINGELING_LIB) $(GLUCOSE_LIB) $(CADICAL_LIB) $(PARAFROST_LIB)
 
 SOLVER_OBJS = $(filter %$(OBJEXT), $(SOLVER_LIB))
 ifneq ($(SOLVER_OBJS),)
